config/routes.rb
Rails.application.routes.draw do

  delete '/users/:id/delete_follow' => 'users#delete_follow', as: 'delete_follow'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :questions do
    resources :answers
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :delete_all
  belongs_to :user
  validates :user_id, presence: true
  validates :question, length: { minimum: 1, message: "question shouldn't be empty" }
  default_scope -> { order('created_at DESC') }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @question = get_current_user.questions
  end

  def new
    @question = get_current_user.questions.build
  end


  def create
    @question = get_current_user.questions.build(post_params)
    if @question.save
      SendEmailWorker.perform_async(@question.id,get_current_user.id)
      flash[:notice]  = 'Question created!!!'
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @question.update(post_params)
      flash[:notice]  = 'Question Updated!!'
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    flash[:notice]  = 'Question successfully deleted!!!'
    redirect_to questions_path
  end

  private
  def set_question
    @question = Question.find(update_params[:id])
  end

  def post_params
    params.require(:question).permit(:question,:id)
  end

  def update_params
    params.permit(:question,:id)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="section">
  <div class="container">
    <% @question.each do |q| %>
      <div class="card">
        <div class="media">
          <div class="media-content">
            <p class="title is-5  "><%= link_to q.question , q  %></p>
          </div>
          <hr />
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<% content_for :page_title,  "Edit your Question" %>
<div class="section">
  <%= simple_form_for @question do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :question, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
  <% end %>
</div>

app/views/questions/index.html.erb
<% content_for :page_title,  "Questions Index" %>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= render 'form' %>

app/views/questions/new.html.erb
<% content_for :page_title,  "Create a new Question" %>
    <div class="section">
      <%= simple_form_for @question do |f| %>
        <div class="field">
          <div class="control">
            <%= f.input :question, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
          </div>
        </div>
        <%= f.button :submit, 'Create new post', class: "button is-success is-outlined" %>
      <% end %>
    </div>

app/views/questions/show.html.erb
<% content_for :page_title,  "Question" %>
<% if admin? || session[:user_id] == @question.user_id %>
<section class="section">
  <div class="container">
    <nav class="level">
      <!-- Left side -->
      <div class="level-left">
        <p class="level-item">
          <strong>Actions</strong>
        </p>
      </div>
      <div class="level-item">
        <% if flash[:notice] %>
          <p class="notice"><%= flash[:notice] %></p>
        <% end %>
      </div>
      <!-- Right side -->
      <div class="level-right">
        <p class="level-item">
          <%= link_to "Edit", edit_question_path(@question), class:"button is-link is-outlined" %>
        </p>
        <p class="level-item">
          <%= link_to "Delete", question_path(@question), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger is-outlined" %>
        </p>
      </div>
    </nav>
    <hr/>
  </div>
</section>
  <% end %>

<section class="section">
  <div class="content">
    <h3 class="container"><%= @question.question %></h3>
  </div>
</section>

<section class="section answers">
  <div class="container">
    <h2 class="subtitle is-5"><strong><%= @question.answers.count %></strong> Answers</h2>
    <%= render @question.answers %>
    <div class="comment-form">
      <hr />
      <h3 class="subtitle is-3">Answer the question....</h3>
      <%= render 'answers/form' %>
    </div>
  </div>
</section>