config/routes.rb
Rails.application.routes.draw do

  delete '/users/:id/delete_follow' => 'users#delete_follow', as: 'delete_follow'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :questions do
    resources :answers
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "questions#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 },
                                    uniqueness: { scope: :name, message: "Username already taken " }
  validates :email, presence: true,
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { scope: :email, case_sensitive: false,
                                 message: "Email already taken " }
  validates :password, length: { minimum: 6, message: "password should be atleast 6 character in length" }

  has_many :answers, dependent: :delete_all
  has_many :questions, dependent: :delete_all

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id",
           class_name:  "Relationship",
           dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  before_destroy :clear_the_session

  public
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  private
  def clear_the_session
    if @user == $current_user
    $current_user = nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers,:delete_follow]
  skip_before_action :authorize, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.where('softDelete = false')
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @question = @user.questions
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_later
        format.html { redirect_to login_path, notice: 'User was successfully created. Login now!!!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_follow
    if params[:title].downcase == "following"
      @user.followed_users.each do |u|
        u.update_column(:softDelete, true)
      end
    elsif params[:title].downcase == "followers"
      @user.followers.each do |u|
        u.update_column(:softDelete, true)
      end
    end
    UserDeleteWorker.perform_async(params[:id],params[:title])
    respond_to do |format|
      format.html { redirect_to user_path, notice: 'Users was successfully destroyed!!' }
      format.json { head :no_content }
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == get_current_user
      session.destroy
      session[:user_id] = nil
      $current_user = nil
      @user.destroy
      respond_to do |format|
        format.html { redirect_to login_path, notice: 'User was successfully destroyed and successfully logged out!!!!' }
        format.json { head :no_content }
      end
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
    end
    end
  end

  def following
    @title = "Following"
    @users = @user.followed_users.where('softDelete = false')
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = @user.followers.where('softDelete = false')
    render 'show_follow'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for($current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "button" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <div class="field">
      <div class="control">
        <%= f.input :name, required: true, autofocus: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :password, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :password_confirmation, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :email, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
          <%=f.input :role, as: :radio_buttons, :collection => [["user", 'user'], ["admin", 'admin']], :checked => ["user", 'user'], wrapper: false, label_html: { class: "radio" }%>
      </div>
    </div>

      <div class="form-actions">
        <%= f.button :submit, class: "button is-success is-outlined" %>
      </div>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for($current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "button" %>
<% end %>

app/views/users/_user.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= link_to user.name, user %></p>
        <p class="subtitle is-6"><%= user.email %></p>
      </div>
      <div class="media-content">
          <%= render 'follow_form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :page_title,  "Update Profile" %>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% content_for :page_title,  "Users page!!" %>
<% if notice %>
  <p id="notice">
    <% notice %>
  </p>
  <% end %>

  <div class="section">
    <div class="container">

    <% @users.each do |user| %>
        <% unless current_user?(user) %>
      <div class="card">
        <div class="media">
          <div class="media-content">
            <p class="title is-5  ">
              <%= link_to user.name , user %>
            </p>
          </div>
          <div class="level-right">
            <% if admin? %>
          <p class="level-item">
            <%= link_to 'Edit', edit_user_path(user), class:"button is-link is-outlined" %>
          </p>
          <p class="level-item">
            <%= link_to 'Delete User', user, method: :delete, data: { confirm: 'The user related posts will also gets deleted, Are you sure?' }, class:"button is-danger is-outlined" %>
            <% end %>
          </div>
          <hr />
        </div>
      </div>
          <% end %>
    <% end %>
    </div>
  </div>

app/views/users/new.html.erb
<% content_for :page_title,  "Signup!!!!" %>
<div class="box">
<%= render 'form' %>
</br>
</div>

app/views/users/show.html.erb
<% content_for :page_title,  "Profile" %>
<p id="notice">
  <%= notice %>
</p>

<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= @user.name %></p>
        <p class="subtitle is-6"><%= @user.email %></p>
      </div>
      <div class="media-content">
        <p class="subtitle is-6">
          <a href="<%= following_user_path(@user) %>">
            <strong>
              <%= @user.followed_users.where('softDelete = false').count %>
            </strong>
            following
          </a>
        </p>
        <p class="subtitle is-6">
          <a href="<%= followers_user_path(@user) %>">
            <strong>
              <%= @user.followers.where('softDelete = false').count %>
            </strong>
            followers
          </a>
        </p>
      </div>
      <div class="media-content">
        <p class="content"><b>Questions Posted:</b> <%= @user.questions.count %></p>
        <p class="content"><b>Questions Answered:</b> <%= @user.answers.count %></p>
      </div>
      <div class ="level-right">
        <p class="content">
          <%= render 'follow_form' %>
        </p>
      </div>
      <p class="content">
        <%= link_to 'Delete my profile', @user, method: :delete, data: { confirm: 'The user related posts will also gets deleted, Are you sure?' }, class:"button is-danger is-outlined" if session[:user_id] == @user.id%>
      </p>
      </div>
    </div>
  </div>
</div>
<%= render 'questions/form' %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section class="content">
      <div><%= link_to "Back", @user, class: "button is-link is-outlined" %></div>
    </section>
    <section class="content">
      <% if admin? %>
      <div><%= link_to ('Delete all ' + @title.downcase + ' users'), delete_follow_path(:params => params, :title => @title ), method: 'delete', :controller => "users_controller", :action => "destroy", data: { confirm: 'The user related posts will also gets deleted, Are you sure?' }, class:"button is-danger is-outlined" if session[:user_id] == @user.id%></div>
      <%end %>
    </section>
  </aside>
  <section class="content">
  <div class="span8">
    <section class="content">
    <span><b><%= @title %></b></span>
    </section>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
  </section>
</div>