config/routes.rb
Rails.application.routes.draw do

  delete '/users/:id/delete_follow' => 'users#delete_follow', as: 'delete_follow'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :relationships, only: [:create, :destroy]
  resources :users
  resources :questions do
    resources :answers
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  validates :question_id, presence: true
  validates :user_id, presence: true
  validates :answer, length: { minimum: 1, message: "Answer shouldn't be empty" }
  default_scope -> { order('created_at DESC') }

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [:create, :edit, :update, :destroy, :set_answer]
  before_action :set_answer, only: [:destroy,:update,:edit]

  def create
    @question.answers.create(post_params.merge({user_id: get_current_user.id}))
    flash[:notice]  = 'New answer posted!!!'
    redirect_to @question
  end

  def edit
  end

  def update
    if @answer.update(post_params)
      flash[:notice]  = "( #{@answer.answer} ) Updated!!!!!"
      redirect_to @question
    else
      render 'answers/edit'
    end
  end

  def destroy
    @answer.destroy
    flash[:notice]  = "( #{@answer.answer} ) Deleted!!!!"
    redirect_to @question
  end

  private

  def set_question
    @question = Question.find(update_params[:question_id])
  end

  def set_answer
    @answer = @question.answers.find(update_params[:id])
  end

  def post_params
    params.require(:answer).permit(:answer)
  end

  def update_params
    params.permit(:id,:question_id,:answer)
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <%= answer.answer %>
        </p>
      </div>
    </div>
    <% if admin? || session[:user_id] == answer.user_id %>
    <div class="level-right">
    <p class="level-item">
    <%= link_to 'Edit', edit_question_answer_path(answer.question,answer), class: "button is-link is-outlined" %>
    </p>
    <p class="level-item">
    <%= link_to 'Delete', [answer.question, answer],
                method: :delete, class: "button is-danger is-outlined", data: { confirm: 'Are you sure?' } %>
    </p>
    </div>
    <% end %>
  </article>

</div>

app/views/answers/_form.html.erb
<div class="section">
  <%= simple_form_for([@question, @question.answers.build]) do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :answer, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-success is-outlined" %>
  <% end %>
</div>

app/views/answers/edit.html.erb
<% content_for :page_title,  "Edit your Answer for question asked" %>
<div class="section">
<%= simple_form_for [@question, @answer] do |f| %>
    <div class="field">
<div class="control">
<%= f.input :answer, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
<% end %>
</div>